---
title: "Untitled"
output: html_document
---

Lieber Herr/Frau XX, 

Im Rahmen des wissenschaftlichen Projekt "IdeoScale" bei der Universität Konstanz, führen wir eine Experten-Umfrage zum Thema Positionierung von Bundestagsmitglieder auf der Links-Rechts Achse. Sie wurden ausgewählt aufgrund ihrem Engagement bei einer der jugend-parteiliche Organisation Deutschlands. Wir sind nämlich der Meinung, dass Ihre Proximität mit dem deutschen politischen Leben Ihnen das Wissen gibt, das wir für unsere Studie brauchen. 

Das Ziel der Studie ist die links-rechts Positionierung von jetzigen Bundestagsmitglieder einzuschätzen. Um dieses Ziel zu erreichen, fragen 25 Mitglieder der jugend-parteiliche Organisationen mittels einer App die Position von zwei Mitglieder des Bundestags zu vergleichen (Screenshot in Anhang). Diese Vergleiche werden wiederholt, bis wir die Position der Abgeordnete präzis einschätzen können. 

Die Studie dauert max. zwei Stunden und wird mit 70€ vergütet. Ihre individuelle Antworte werden nicht veröffentlicht, sondern benutzt um eine aggregierte Messung zu berechnen. Die Registration für die Studie erfolgt über folgendes Formular.

Wir würden uns sehr freuen, wenn sie an dieser Studie teilnehmen würden. Falls sie Fragen haben, stehen wir zur Verfügung.

Vielen Dank im Voraus für Ihre Wissen und beste Grüße, 

Simon und Benjamin
Projekt IdeoScale


